# Generated by Django 5.2.3 on 2025-07-01 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProducaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.IntegerField()),
                ('tipo_produto', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produção Diária',
                'verbose_name_plural': 'Produções Diárias',
                'ordering': ['-data'],
            },
        ),
    ]
