# Generated by Django 5.2.3 on 2025-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producaodiaria',
            options={'ordering': ['-data', 'bairro'], 'verbose_name': 'Produção Diária', 'verbose_name_plural': 'Produções Diárias'},
        ),
        migrations.RemoveField(
            model_name='producaodiaria',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='producaodiaria',
            name='tipo_produto',
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='ciclo_ano',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='comercio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='eliminados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='fechados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='nome_responsavel',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='numero_identificacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='outros',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='ponto_estrategico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='recuperados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='recusas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='residencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='terreno_baldios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='total_geral',
            field=models.IntegerField(default=0),
        ),
    ]
