# Generated by Django 5.2.3 on 2025-07-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_alter_producaodiaria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producaodiaria',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='producaodiaria',
            name='total_geral',
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='numero_quarteirao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° do Quarteirão'),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='semana_epidemiologica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Semana Epidemiológica'),
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='total_imoveis_abertos',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total de Imóveis Abertos'),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='comercio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='nome_responsavel',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='numero_identificacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='outros',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='ponto_estrategico',
            field=models.IntegerField(default=0, verbose_name='Ponto Estratégico'),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='residencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='terreno_baldios',
            field=models.IntegerField(default=0, verbose_name='Terreno Baldio'),
        ),
    ]
