# Generated by Django 5.1.6 on 2025-07-03 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_remove_producaodiaria_observacoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producaodiaria',
            name='numero_identificacao',
        ),
        migrations.RemoveField(
            model_name='producaodiaria',
            name='total_imoveis_abertos',
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaodiaria',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producoes_diarias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='ciclo_ano',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='nome_responsavel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='numero_quarteirao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='ponto_estrategico',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='semana_epidemiologica',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producaodiaria',
            name='terreno_baldios',
            field=models.IntegerField(default=0),
        ),
    ]
